### ISSUE TITLE
transform problems

### ISSUE THREAD

**Issue by shudson310** [dita-community/org.dita-community.glossary.preprocess#2]
Finally got the plugins installed and integrated to OT v3.3.1. Set the parameters in the transform scenario (oXygen) and get these errors in the transform:
```
map-mapref:
   [mapref] Static error near {...litWords($text, $lang, $deb...} in expression in xsl:variable/@select on line 407 column 103 of i18n-utils.xsl:
   [mapref]   XPST0017: Cannot find a 3-argument function named
   [mapref]   {http://org.dita-community/i18n/saxon-extensions}splitWords()
   [mapref] Static error near {...litLines($text, $lang, $deb...} in expression in xsl:variable/@select on line 425 column 104 of i18n-utils.xsl:
   [mapref]   XPST0017: Cannot find a 3-argument function named
   [mapref]   {http://org.dita-community/i18n/saxon-extensions}splitLines()
   [mapref] Static error near {...tLines($text, $lang, $debug...} in expression in xsl:variable/@select on line 440 column 7 of i18n-utils.xsl:
   [mapref]   XPST0017: Cannot find a 3-argument function named
   [mapref]   {http://org.dita-community/i18n/saxon-extensions}splitLines()
   [mapref] Static error near {...$fontSize, $fontStyle, $deb...} in expression in xsl:variable/@select on line 496 column 7 of i18n-utils.xsl:
   [mapref]   XPST0017: Cannot find a 5-argument function named
   [mapref]   {http://org.dita-community/i18n/saxon-extensions}getRenderedLength()
```

Seems liike a problem with the sorting?

**Comment by shudson310** [comment]
Here's the Java stack trace:
`dita-ot-3.3.1/plugins/org.dita.base/build_preprocess2.xml:105: java.lang.RuntimeException: javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
	at org.dita.dost.module.MaprefModule.init(MaprefModule.java:57)
	at org.dita.dost.module.MaprefModule.execute(MaprefModule.java:72)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:182)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:834)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:158)
	at org.dita.dost.module.MaprefModule.init(MaprefModule.java:54)
	... 31 more
Caused by: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:742)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:155)
	... 32 more
Caused by: net.sf.saxon.trans.XPathException: Errors were reported during stylesheet compilation
	at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:260)
	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:106)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:739)
	... 33 more
`

**Comment by drmacro** [comment]
There must be a configuration error somewhere--I'll track it down.

**Comment by drmacro** [comment]
Have reproduced the failure. Must be an issue with the version of the common.xslt library that is in the registry.

**Comment by drmacro** [comment]
The issue is in the mapref stage--the MaprefModule doesn't configure the transformer with the extension functions so the transform fails.

I don't think there's a workaround so will require fixing the OT to register extension functions.

I'm not sure how this worked at all because this is not a change to OT code in 3.3.1 or anything that I can tell, but obviously it worked for me on my machine. But how?

**Comment by shudson310** [comment]
Are you running via command-line, or using a tool like oXygen? I've been running with oXygen.

**Comment by drmacro** [comment]
I'm running from the command line. The only way that using Oxygen might make a difference is running with the licensed PE or EE version of Saxon might avoid the failure, otherwise I don't see how this could have ever worked :-(

**Comment by AndeeZee** [comment]
Hello!
Any update on this one? I'm running in the exact same issue and thought it would be related to the i18n plugin, where I posted some build issues today.

Please let us know, if we can expect a solution on the short run for this.

Thanks,
Andy
